spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RameshSv/cloud-config-repo
          defaultLabel: master
          searchPaths: '{application}'
management:
  endpoints:
    web:
      exposure:
        include=*:

server:
  port: ${port:8888}

